CrashpointF13/CrashpointF13

code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/jobs/job_types/job.dm
Removes the pesky ability to pick your genitals.
This solves the problem in which the same 7 foot wang futa ERPer would show up and instantly be able to shit on everything the server stands for with it's disturbing fetish ERP.
Tested it in a private game, seems to work alright. Will post screenshots.
:cl:
tweak: Genitals are now based on your gender
del: You can no longer mix and match your genitals
/:cl:
=> Removes Ability to Select Genitals as a Preference

_maps/map_files/Pahrump/Dungeons.dmm, _maps/map_files/Pahrump/Pahrump.dmm, code/game/objects/effects/landmarks.dm, code/game/objects/items/cards_ids.dm, code/game/objects/items/devices/radio/intercom.dm, code/game/objects/items/fallout13misc.dm, code/game/objects/items/storage/boxes.dm, code/game/turfs/simulated/minerals.dm, code/modules/fallout/machinery/light_sources/bar.dm, code/modules/fallout/mob/simple_animal/mobs/supermutant.dm, code/modules/jobs/job_types/legion.dm, code/modules/mob/living/simple_animal/hostile/ghoul.dm, code/modules/mob/living/simple_animal/hostile/wastebots.dm, code/modules/mob/living/simple_animal/spawner.dm, code/modules/shuttle/f13.dm, code/modules/vehicles/wasteland/buggy.dm, tgstation.dme
- - -
Gungeons are far more logical, rather than being "SIXTY THOUSAND MOBS ECKSDEEE"
- - -
Map:
- As above.
- In the northern part of the Sewers, you'll start to come across toxic waste.
- De-Oasis and de-babyproofs some areas.
- Tunnels between the Raiders and Western part of the map blocked off. Mostly. There's still a method of travel through the rat's nest, if you don't want to go south-west.
- - -
Balance:
- Gibtonite can now once again spawn.
- Ghouls rebalanced health wise.
- 'Borgs rebalanced health wise.
- - -
Other:
- Oasis flags removed. Gang gang, anti-ERP Fiend gang.
=> Dungeon Reworks

code/__DEFINES/jobs.dm, code/modules/jobs/job_types/den.dm, code/modules/jobs/jobs.dm
& other role stuff. Fixes Legionnaire, NCR Specialist, Shopkeeper, Villager, Chief and Shaman showing up in the "Miscellaneous" section of the Wasteland Census. All the tribal roles are moved to the Wasteland section because I decided to do it that way.
It looked kind of stupid so I thought I'd fix it.
Tested it by hosting locally. Seemed to work just fine.
:cl:
tweak: Legionnaire and NCR Specialist show up in the correct spot on the census
tweak: Tribal roles go to Wasteland instead of something that didn't exist
/:cl:
=> Fixes some roles showing up as "Miscellaneous" in the Wasteland Census (Crew Manifest)

code/modules/crafting/recipes.dm
Title.
Turbo can now be crafted with the following:
-1 broc flower
-1 slab of cazador meat (to remplace the cazador poison gland which isn't in the code)
-1 jet
-1 spraycan (due to Turpentine being nearly impossible to find and the Fallout wiki mentioning that it's jet attached to a can of hairpray)
Due to the very low amount of Turbo around the map (I think there is only 3-4 in total) and due to it having been nerfed to the ground by DR I think it would be a good idea having people be able to produce it.
Did it locally like usual and it's working.
:cl:
add: crafting option for turbo
/:cl:
=> Adding Crafting Recipe for Turbo

code/modules/mob/living/simple_animal/hostile/ghoul.dm
This is my first ever PR so I have no idea what I'm doing.
Nerfs certain ghouls to be weaker/slower.
Ghouls are somehow pretty hard to kill, using up entire magazines of most guns found on the wastelands. 
It seems to be pretty ok on a local server.
:cl:
tweak: Nerf Ghouls.
/🆑
=> Ghoul Nerf

code/modules/projectiles/guns/ballistic/revolver.dm
there was no fire delay to the police revolver, adds a fire delay of 1
added a fire delay to the police pistol
https://github.com/CrashpointF13/CrashpointF13/issues/52
I don't see why this would require testing.
:cl:
- added fire delay to police pistol
/:cl:
=> add fire delay to revolver

code/modules/mob/living/simple_animal/hostile/ghoul.dm
Ghouls (and subsequently most mobs) being bullet sponges was one of Desert Rose's PVE changes I guess. I changed ghouls back (close) to what they used to be on Bad Deathclaw. A regular ghoul shouldn't take more than an entire mag of 9mm. Now they don't!
Ghouls have no business being bullet sponges. Rotten, sinewy mutant humans who are practically falling apart shouldn't absorb entire magazines. I'm thinking maybe I've made them too weak again, but we'll see I guess.
Tested it on a local hosted instance.
:cl:
tweak: tweaked ghoul health back to reasonable levels
balance: ghouls no longer bullet sponges
/:cl:
=> Changes Ghouls from Bullet Sponges back to How They Used To Be

code/game/objects/items/weaponry.dm
I i buffed throwing spears because, with how hard they are to transport,  their slow down and their rate of fire, 25 damages was not enough, so i went with the old 35 bad deathclaw had, next to that i also nerfed the embed chance from 80% to 50%.
throwing spears areimportant for legion, they are part of their identity on the server, giving them a bit of use seem to be a good idea.
More damages on spears, less embed.
=> throwing spears buff

code/modules/food_and_drinks/drinks/drinks/bottle.dm
Now they explode in 10 seconds, also remove the "You're not sure this was a good idea" that DR added to the text that appear when you lit a molotov.
Everyone hated the fact that a molotov could explode in your face right after being lit.
Locally and it's working.
:cl:
fix: molotovs exploding after less than a second of being lit.
removed: "You're not sure this was a good idea" from when a molotov is lit.
code: mention in the molotov codes that the numbers that shows when the molotov explode
/:cl:
=> Molotovs Fix

code/modules/mob/living/carbon/alien/alien_defense.dm, code/modules/mob/living/carbon/alien/larva/larva_defense.dm, code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/carbon/monkey/monkey_defense.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/silicon/robot/robot_defense.dm, code/modules/mob/living/silicon/silicon_defense.dm, code/modules/mob/living/simple_animal/animal_defense.dm, code/modules/projectiles/projectile.dm
Replaces userdanger (big text) with boldannounce (standstorm goes off text).
This increases chat performance on combat situations by about 40% , meaning if you have a bad computer, it wont crash when being chat spammed by alot of projectiles because of the ugly wall of text.
Tested on dreamdaemon 513.1522, working as expected.
:cl:
fix: Goonchat is no longer compared to a bitcoin miner.
/:cl:
=> Goonchat fix (merge this or die edition)

code/modules/crafting/recipes.dm
Makes stimpaks, healing powder and their superior versions 50% less expensive for their part.
This does it so that it's less time and resource consuming, with less stray plants on the ground taking up some precious processing space. Also #53 request comment.
Tested locally.
:cl:
balance: Advances in plant technology increases recipe efficiency.
/:cl:
=> Medical crafting rework.

code/modules/food_and_drinks/drinks/drinks/bottle.dm
After a couple of people saying they wanted them to be like how they where back on BD, I changed it so now they don't self destroy.
People wanted to carry lit molotovs in their bags, might as well let them do it. Plus I think that the fact that a molotovs can explode on their own after being lit make people not want to use them in the first place.
Locally
:cl:
tweak: now molotovs doesn't explode after a certain amount of time.
/:cl:
=> Reverting Molotovs

code/modules/crafting/recipes.dm
Removes the H&K CAWS and City-Killer Shotgun from crafting.
I did this because an automatic shotgun with like 12 round capacity is fucking retarded powergame BS and so is gun crafting in general. But we'll have to settle with removing the city-killer.
tested locally, seems to work just fine.
:cl:
del: Removes some t5 guns from crafting menu.
/:cl:
=> Removes H&K CAWS and City-Killer Shotgun from crafting

code/modules/clothing/head/helmet.dm, code/modules/clothing/suits/armor.dm
Changes around ranger combat armor to make it more in line with 'medium armors' instead of having it be a disguised heavy armor.
Gives the same slowdown modifier that legion currently has to most ranger and scout armors, as to allow them to scout without inevitably getting caught.
Fixes some inconsistencies between armor pieces and their headgears and tweaks T-51 alowdown a little.
Small buff to heavy decanus loadout-specific armor, to not make it be essentially a worse veteran legionary set.
Puts the ranger trail jacket on par with the now unused ranger recon duster, as they belonged to the same role and trail jacket needs some upside after its speed boost was heavily nerfed.
Mostly as cited above. 
Tested locally.
:cl:
fixes armor/headgear inconsistencies, balances ranger/scout armor …
=> Small Armor Tweaks and Fixes

code/game/objects/effects/spawners/f13lootdrop.dm
The LARP is back, hopefully you get good RNG.
I removed the one ring from the possibility of getting spawned and added back Enclave PA. This WAS a thing back on BD so I don't know if later on after I left they removed it or what, but it seems redundant since the only place T5 is found is in the enclave bunker.
I don't want a bus item, nor a LOTR reference appearing on normal rounds.
I want to LARP as enclave, I'm sure others do as well. The robust will be able to nab these I suppose?
Should be fine, I made sure to leave no stone unturned when tweaking shit unlike my last PR.
N/A even if I did it would just be the enclave bunker with some enclave powerarmor.
:cl:
del: Removed the One Ring from rotation/normal gameplay.
add: Enclave Power Armor can once again be found in the Enclave bunker. …
=> [READY] Adds back enclave powerarmor to the T5 armor pool also removes ring.

code/modules/clothing/suits/armor.dm
Made it so the tesla powerarmor has the same slowdown as T51b and a more consistent description.
New Vegas had tesla powerarmor as medium armor, not heavy like the remnants armor, our timeline is closest to that of NV so I'll use that as a basis. "The Gannon family Tesla armor is classified as medium armor" - Fallout Fandom wiki.
I would test-merge this considering it's a balance change but given that it's high-class armor that might not be the best to just test it in-game on live rounds.
Just a simple variable and description change.
:cl:
tweak: You can now move faster in advanced tesla power-armor.
/:cl:
=> Tesla powerarmor is now medium armor.

code/modules/crafting/guncrafting.dm
Adds the ability for the press to actually make ammo.
Crafting update messed with ammo crafting, and this did get unnoticed.
Locally under sleep deprivation.
:cl:
fix: The pre-war press is useful now.
/:cl:
=> Pre-war press revival.

_maps/map_files/Pahrump/Pahrump.dmm
Replaced two matrix turfs with two different turfs.
There's no reason these people should be able to walk into a wall and just boof out of existence. If someone wants to bail for the round, they can go chill in their bed or some shit and just snooze off and/or ghost. If they feel they REALLY need to get removed, and admin can teleport them to a matrix or just delete them from existence. The fact they can just head on out into a matrix through a wall is absurd. 
I've already seen Brotherhood straight dipping during raids in the past.
I confirmed that there is in fact no longer a matrix. 
You're welcome. Merge it.
=> Removes the Matrix from BOS/Vault

_maps/map_files/generic/CentCom.dmm, code/datums/ert.dm, code/game/objects/items/devices/radio/encryptionkey.dm, code/modules/antagonists/ert/ert.dm, code/modules/clothing/glasses/f13.dm, code/modules/clothing/outfits/standard.dm, code/modules/projectiles/guns/energy/laser.dm
Changes Deathsquad to be more in line with something thematically appropriate.
- - -
Edits:
- Enclave Fireteam has replaced DS.
- Minor edits to CentCom to remove overpowered laser weaponry from being readily accesible.
=> Deathsquad Changes

interactions/lewd/lewd_interactions.dm
Currently if the body doesn't have a client in it then it doesn't matter whether the player originally had erp verbs allowed or not, so a lot of people grief by killing someone to bypass the erp verb restriction. This PR will make it so that you can no longer use erp interactions on people without a client. This also means that you cant use erp interactions on humans that wouldn't normally have a client like the raider NPCs or maybe a slime copy of yourself but honestly at that point just use custom emotes if you really want to or you're probably just doing lrp shit if that's too hard. But if people want to still be able to diddle the raider npc's then I'll make it just check if the user is alive or not.
Lots of people complaining about this, I've seen a few people from other servers who …
=> Removes erping dead/catatonic people

code/game/objects/items/storage/boxes.dm, code/modules/projectiles/ammunition/ballistic/pistol.dm, code/modules/projectiles/ammunition/ballistic/revolver.dm, code/modules/projectiles/ammunition/ballistic/rifle.dm, code/modules/projectiles/ammunition/ballistic/shotgun.dm, code/modules/projectiles/ammunition/ballistic/sniper.dm, code/modules/projectiles/projectile/bullets/shotgun.dm
Changes the slug from 50dam/20ap to 40/15 with 7 max range. Now, slugs are not objectively better than most rifles in the game and are instead just a situational alternative to buckshot. Buckshot is better when PBing unarmored targets, while slugs are better when fighting someone outside of PB range and with armor, but not at a capacity outside of what would be considered CQC. Buckshot has falloff, Slugs have a max range. Also, if the person you're fighting doesn't take advantage of the max range, you're effectively using a hunting rifle with a higher ammo cap and .308, although the riot shotgun is still autistically overpowered so whatever.
also adds small descriptions to most bullet types so you know what they go to or what they are used against.
Slugs are fucking retarded. It turns …
=> slug rebalance/bullet description changes

interactions/lewd/lewd_interactions.dm
Scuffed. Didn't realize it during test merges or looking over the code. Enables the ERP of people regardless of their preferences.
View #190.
=> Revert "Removes erping dead/catatonic people"

code/modules/jobs/job_types/wasteland.dm
Adds the new "Tribal" outfit loadout for Wastelanders. 
The Tribal kit includes:
* Tribal Armor - Suit
* Tribal Rags - Uniform
* Handwraps - Gloves
* Foot Rags - Shoes
I quite enjoy playing as a tribal and since the tribal job is currently not used, this offers players a way to play as a tribal right off the bat instead of having to craft the armor. Breaks immersion to spawn in with normal waster clothes as a tribal character. Also offers more opportunities for roleplay!
:cl:
add: Tribal loadout added for Wastelanders.
/:cl:
=> Tribal loadout for Wastelander role

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/Pahrump/Pahrump.dmm, code/game/objects/structures/crates_lockers/closets/utility_closets.dm, code/modules/clothing/suits/f13.dm, code/modules/jobs/job_types/ncr.dm, code/modules/reagents/chemistry/reagents/toxin_reagents.dm
- - -
Edits:
- Hazmat suit now available, replacing both the Radsuit and Biosuit in everything. They're rarer than the aforementioned, however, so use them properly.
- FEV is now much more deadly in regards to radiation build up, but doesn't immediately put you into cellular crit now. At least, it shouldn't. This is alongside it having near no toxin power, as that wasn't the point of it in the first place. Especially not at FIVE.
- Scout Specialist of the NCR has lost their scoped rifle. They retain the binoculars.
- A shaving razor has been added to Sunnydale for the NCR. Start enforcing hair restrictions.
- Recharger stations made less common. Borgs now have a reason to ration cell charge until late round.
=> General Rebalances

code/__DEFINES/radiation.dm, code/modules/mob/living/carbon/human/species_types/ghoul.dm
- - -
Additions:
- Ghouls may now drink radium to heal. This stacks with what's to follow.
- Ghouls, when irradiated, now heal over time at a good pace. You may stack this with radium, alongside the fact that the only way to become irradiated is to consume radioactive material.
- Glowing Ones now properly emit radiation.
=> Ghoul Buffs

code/game/machinery/recycler.dm, code/game/mecha/equipment/tools/mining_tools.dm, code/game/objects/effects/spawners/f13lootdrop.dm, code/game/objects/items/holy_weapons.dm, code/game/objects/items/kitchen.dm, code/game/objects/items/melee/misc.dm, code/game/objects/items/stacks/sheets/glass.dm, code/game/objects/items/twohanded.dm, code/game/objects/items/weaponry.dm, code/modules/antagonists/changeling/powers/mutations.dm, code/modules/antagonists/cult/cult_items.dm, code/modules/clothing/suits/armor.dm, code/modules/crafting/recipes.dm, code/modules/food_and_drinks/drinks/drinks/bottle.dm, code/modules/hydroponics/hydroitemdefines.dm, code/modules/jobs/job_types/wasteland.dm, code/modules/mining/equipment/kinetic_crusher.dm, code/modules/mining/equipment/mining_tools.dm, code/modules/mining/lavaland/necropolis_chests.dm, code/modules/mob/living/carbon/human/species_types/shadowpeople.dm, code/modules/paperwork/pen.dm, code/modules/projectiles/guns/energy/special.dm, code/modules/projectiles/guns/magic/staff.dm, code/modules/surgery/tools.dm
Fixes a few bugs, and cleans up some component related code that I noticed wasn't set up right(you add the component in ComponentInitialize() so that you can have the option to override that method so that the components aren't added, which you can't do if it's in Initialize())
Changed the badlands armor to be of the raider armor type so that it isn't weaker than the other armors and because I thought that was an oversight, labeling it as a balance change on the changelog so that it doesn't look like I'm trying to sneak this in.
Yes I spawned in game and tested them
:cl: Sneakyrat
balance: Raider badlands armor now has the same stats as other raider armors(it used to be lower)
fix: Fixed being able to use super stimpaks and empty stimpaks for the super stimpak recipe
fix: Fixed being able …
=> Various bug fixes

code/modules/fallout/mob/simple_animal/mobs/supermutant.dm
Nrf the super mutant health from 450 to 350. I think its better that way since 450 is only 50 hp lower than a deathclaw, making dungeons near impossible to do without faction gears, or advanced loot.
heavy ranged mutant are not touched.
=> super mutants health nerf

interactions/_interaction.dm, interactions/lewd/lewd_interactions.dm
I forgot to test #190 with multiple connections, but I just learned how so I tested this one and it works, while doing so I also discovered another bug and fixed that one as well.
:cl: Sneakyrat
tweak: Removes ERPing SSD/dead players for real this time
fix: Fixes being able to use interactions from your dead body
/:cl:
=> Removes ERPing SSD/dead players for real this time

code/__DEFINES/misc.dm, code/datums/traits/neutral.dm, code/modules/library/soapstone.dm, code/modules/surgery/bodyparts/dismemberment.dm
- - -
Balance:
- Disembowelment has been re-enabled. Currently, it only functions on targets that aren't fully conscious, meaning you can't be disembowelled while mid-combat.
To disembowel, it requires you to have put the target into anything other than standard condition. This includes, but isn't limited to: Soft-Crit, Hard-Crit, Unconsciousness.
- Lowers the defib timer to five minutes, from fifteen.
- - -
Additions:
- You may now get a soapstone through a new neutral trait.
- - -
=> Balance Changes

code/modules/mob/say.dm
A bunch of nerds started whining about how they couldn't use the nonhotkey mode to speak. Now, you can! Though, say indicators won't show up when using nonhotkey mode to speak because that's simply how they work.
Bitches whine.
Coders suffer.
UwU
Tested it on local machine and it works great!
:cl:
fix: fixed say indicators to allow nonhotkey use.
/:cl:
=> Say Indicator Fix

_maps/map_files/Pahrump/Pahrump.dmm
Replaces the faction bases on Pahrump, brings back some old areas and updates mobs to make looting certain locations harder.
NCR base + Old town that was below it re-added to replace the empty void of tribal town.
https://i.imgur.com/pGQRF1n.png
https://i.imgur.com/wGd0jlh.png
Updated Prior Legion Camp
https://i.imgur.com/QK9yKN2.png
Made it so to access workbench you don't have to break into shop. Also, made it so settlers don't potentially spawn outside into hazardous weather.
https://i.imgur.com/cVqMToi.png
Buffed certain areas with mobs dependent on loot level.
Minor note: While unchanged, I noticed that radiation is actually something caused by area.
=> Pahrump Changes

_maps/map_files/Pahrump/Pahrump.dmm
Oxygen tanks in Centurion's cabin
So that the powerfist can work.
local machine.
:cl:
add: Add oxygen tanks in Centurion cabin
/:cl:
=> Add oxygen tanks for Legion on Pahrump

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/BoxStation/Dungeons.dmm, _maps/map_files/Pahrump/Pahrump.dmm, code/_onclick/hud/hud.dm, code/modules/fallout/turf/walls.dm, code/modules/mob/living/carbon/human/species.dm
- - -
Map:
- Changes various areas to what they were intended. The ghoul spawner on Sunnydale, for example, has been removed.
- - -
Other:
- Plasmafire is now the default hud.
- A certain wall type has been renamed to assure there's no mixup.
=> QoL Changes
