CrashpointF13/CrashpointF13

_maps/map_files/Pahrump/Pahrump.dmm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm
code/modules/customitems/item_defines.dm
code/modules/jobs/job_types/bos.dm
code/modules/jobs/job_types/vault.dm

continuation

---

code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm

Revert "Pa buff"

---

_maps/map_files/Pahrump/Pahrump.dmm
code/modules/mob/living/emote.dm

fixes /mes and corporal spawns

hotfix gang

---

code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm
code/modules/crafting/tailoring.dm

Did some armors changes in an attempt to undo what DR did.
-Fixed the metal armors so that they dont start off dark colored for some reasons.
-Removed the "strange" metal armor sets, the "dark" combat armors set and the combat cloaks.
-Re-added the tesla armor set, the desert ranger set and the bmetal armor to the armor loot pool.
-Made some armor spray paintable! The armors that can now be colored is the metal armors, helmets and combat armors.
I and some people didn't liked the changes they did to the armors, so the point of this pull is an attempt to undo most of these changes. Main problems of their changes where that most metal armors where dark colored for some reasons and that you couldn't get the Desert Ranger or the Tesla armor anymore.
Also made some armor spray paintable so …

Some armor changes

---

_maps/map_files/Pahrump/Pahrump.dmm

Removed the old tribal base and replaced it with a much smaller version. Also fixed some areas and added dirt patches around the map.
The tribal base was too big, also I hated the necropolis shit DR used for it. So yup.
Locally tested with no issues. B)
https://gyazo.com/65022502286073407c3152e4e57fbc6d (im too lazy to take a normal screenshot, sorry)
:cl:
add: tribal base
add: dirt
del: covert oddity's taint
/:cl:

Tribal map changes plus details

---

_maps/map_files/Pahrump/Pahrump.dmm

gives the tribals 3 sets of both female and male tribal outfits, 3 sets of the old tribal armor, 2 bows, 4 arrows, and gives them their workbench back.
added 2 shacks in the big wasteland area because i wanted to.
also gives the NCR a workbench, seeing as how literally everyone else gets one at round start.
also fixes the walls around the farm in kebab so they don't glow.
tweak good 
locally
no
:cl:
add: stuff
add: easter egg
del: fucking space areas in kebab
/:cl:

minor tweaks plus 2 shacks

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm
code/__DEFINES/jobs.dm
code/game/objects/effects/landmarks.dm
code/game/objects/items/cards_ids.dm
code/game/objects/items/twohanded.dm
code/game/objects/items/weaponry.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm
code/modules/crafting/recipes.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/projectile/bullets/revolver.dm
code/modules/projectiles/projectile/bullets/shotgun.dm
code/modules/projectiles/projectile/bullets/sniper.dm

- - -
Jobs:
- Librator added to Legion.
- Rangers touched on. Loadouts changed.
- - -
Balance:
- Various armors given slowdown or negative slowdown, to counteract the changes previously mentioned.
- Standard Rangers can now get the Veteran Ranger armor in a Veteran Loadout, but it provides slowdown, and isn't as good as the Elite Veteran Armor, that the actual Veteran Ranger gets.
- Various projectiles changed damage wise. AMR now has a 1 of dismemberment for standard rounds - given it's a rather massive anti-armor projectile with very limited ammunition.

Continual Rebalances

---

code/modules/mob/living/silicon/robot/robot_modules.dm

Removes flamin laser

---

code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm

Modifies job timer stuffs
closes #58

Timer stuffs

---

code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm

Title, fixes rangers zyooming across the map at lightspeed.
*scream

Reduced Armor Slowdown/Increase all around

---

code/modules/clothing/under/f13.dm
code/modules/mob/living/emote.dm
code/modules/mob/living/living.dm

Surrender now shows up in the admin log. Resolves #68 
Better for admuns
:cl:
add: Surrender logging
fix: remove code dupe
/:cl:

Surrender logging, fixes dupe.

---

code/modules/hydroponics/grown/xander.dm

Modifies the age and maturation related variables to regulate their growth pattern.
Makes it so that the plant shows their sprites fully, and doesnt look stupid by having maturated at 1 age. (see their counterpart broc)
This has been tested on a local machine and is working properly.
:cl:
tweak: Xander has been updated with a new growth pattern.
/:cl:

Xander tweak.

---

code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm
code/modules/projectiles/projectile/bullets/rifle.dm

so, the libritor's armor was way too good, had power armor stats, while not having the same slowdown as the broken PA, so i gave it something more on part with the cent's armor
-25 to helmet and armor against bullets, -5 on helmet and armor against melee, +5 on helmet and armor against laser
the role was just way too tanky, for something the legion get 2 times.

libritor nerf

---

code/modules/jobs/job_types/vault.dm

Vault being up to shinangence, this is until we can work with them a bit. Requested by coral.

Disable vault job slots

---

code/controllers/subsystem/vote.dm
code/modules/awaymissions/mission_code/Academy.dm
code/modules/shuttle/emergency.dm

Title
Shuttle timer too looong, also fix.
:cl:
tweak: Shuttle time reduced
fix: fixed auto map voting
/:cl:

Fix map vote, shuttle time reduced.

---

code/modules/goonchat/browserassets/css/browserOutput.css
interface/stylesheet.dm

Does what #80 did, but in a large scale.
From the overall sucess of the previous PR, i've decided to increase the range.
Tested previously as stated.
:cl:
:fix:Userdanger now has a new style.
/:cl:

Goonchat 1.01

---

code/modules/jobs/job_types/bos.dm
code/modules/jobs/job_types/den.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/vault.dm
code/modules/jobs/job_types/wasteland.dm

Increases job lock timers.
Lotta people complaining the timers were to short, I tend to agree with them.
:cl:
tweak: tweaked job timers
/:cl:

Time changes

---

code/controllers/subsystem/vote.dm

Just does a thing to fix another thing.

Transfer Tweak

---

code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/playsound.dm
code/modules/admin/verbs/randomverbs.dm

Boring admun stuff

---

code/datums/weather/weather_types/radiation_storm.dm

makes the alarm sound off twice so people don't get caught off guard by sudden rad-storms

rad-storm alarm fix

---

code/datums/weather/weather_types/radiation_storm.dm
code/game/objects/items/powerfist.dm

Reverts powerfist to how it use to be in BD, only got removed because of a salt pr.

Powerfist revert

---

code/modules/food_and_drinks/recipes/food_mixtures.dm
code/modules/hydroponics/grown/xander.dm
code/modules/reagents/chemistry/machinery/chem_dispenser.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/reagents/chemistry/recipes/others.dm

**CHANGES & FIXES**
- Dough is now made with... Brahmin... Milk... You now need a Brahmin in order to make the staples of food!
- Fixed a Typo with the dispenser.
- You can now create boiled water from dirty water. Boiled water is mostly safe. Mostly...
- Alcoholism's views on the bread making world thanks to that one confusing change
**WHAT NEXT?**
- Embracing inner Bay-Dev and pressing "Delete" on a bunch of recipes/a food overhaul to better fit the Fallout Environment!
- Embracing inner-city roots and reworking Chem-production to be even more hoodlum as fuck. 
- Make better buildable cover/let outposting be an actual fucking thing
- Better Power-Armor mechanics so BoS aren't just a bunch of wannabe white-knights and actually need to upkeep their fancy shmancy stuff, and rewarding …

Alcoholism Update 1.1: 'Till the Cows come Home

---

_maps/map_files/Pahrump/Pahrump.dmm

fixes legion base
carl
carl
carl
:cl:
carl
/:cl:

\legion basefix

---

_maps/map_files/Pahrump/Pahrump.dmm

Gives legion spare outfits in the poopie legionary huts and adds a medical room as an extension to the slave pens.
I am biased and purposely left these out until now.
:cl:
fix: legion base
/:cl:

Legion outfits and medical room

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm
code/game/machinery/doors/city_gate.dm
code/modules/fallout/turf/walls.dm
code/modules/jobs/job_types/legion.dm

Corrections.

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm
code/modules/mob/living/simple_animal/hostile/alien.dm

- - -
Edits:
- Fixes DR Wanamingo garbage. The Wanamingo no longer replaces the entirety of the Alien subpaths.
- - -
Addition:
- Genetics returned to the Vault, in a special way.

General Fixes

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm
_maps/map_files/generic/CentCom.dmm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/silicon.dm
code/modules/jobs/jobs.dm

Many corrections.

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm
code/modules/food_and_drinks/food/condiment.dm
code/modules/food_and_drinks/recipes/food_mixtures.dm
code/modules/mob/living/simple_animal/hostile/tunnelers.dm
code/modules/projectiles/guns/misc/grenade_launcher.dm
code/modules/projectiles/projectile/beams.dm
code/modules/research/designs/weapon_designs.dm
code/modules/research/techweb/all_nodes.dm

- - -
Map:
- Both the Sunnydale and Pahrump Brotherhood now have slave collars.
- Sunnydale refinery given proper conveyor belts.
- Vault walls near the Door upped to be indestructible. This is only for walls in the immediate vicinity.
- Moved Steve. I hope.
- Vault given a prototype clone board for experiments. If this turns out to be an issue, it's very easy to remove.
- - -
Edits:
- Brahmin milk is no longer used for the dough recipe, as it was intended for when water was far more scarce.
- Tunnelers/Spore Carriers now changed in what they both give chem wise. Venom and Tirizene, respectively.
- Tech Nodes given a semi-minor facelift, via the re-addition of many firearms, mechs and some new material.
- - -

Brahmin Milk 2

---

code/modules/clothing/suits/armor.dm
code/modules/jobs/job_types/ncr.dm
html/rules.html

Minor rule adjustment.
Thematic change for Rangers.

Rules & Rangers

---

code/modules/projectiles/projectile/bullets/shotgun.dm

no longer staminacrits in 2 bullets

fixes mech scattershot

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/BoxStation/Dungeons.dmm
code/game/objects/effects/spawners/f13lootdrop.dm
code/game/objects/items/granters.dm
code/modules/fallout/mob/simple_animal/mobs/eyebot.dm
code/modules/mob/living/simple_animal/hostile/wastebots.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/research/techweb/all_nodes.dm

- - -
Edits:
- Sunnydale loot in Mountain Bunker and Enclave Bunker given far higher levels of gear to compensate for difficulty. This includes two PA training books, alongside a Piloting book.
- Positronics now once again obtainable via Technodes.
- Mentats practically makes you immune to brain damage, alongside giving minor levels of unconscious resist. This isn't touching the oxy-loss it healed prior, as that still exists.

General Buffs

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm
code/datums/looping_sounds/item_sounds.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/game/objects/items/melee/misc.dm
code/modules/crafting/recipes.dm
code/modules/fallout/obj/explosives.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
code/modules/mob/living/simple_animal/hostile/wastebots.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/vehicles/_vehicle.dm
code/modules/vehicles/wasteland/motorcycle.dm

Causes the AMR to knock you on your ass all but 5% when firing from the hip.

Hopeful AMR Rebalance

---

_maps/map_files/BoxStation/BoxStation.dmm
code/game/objects/items/stacks/f13Cash.dm
code/modules/fallout/misc/gang_items.dm
code/modules/fallout/misc/gangs.dm
code/modules/mob/living/simple_animal/hostile/ghoul.dm
code/modules/vehicles/wasteland/motorcycle.dm

---
Bugfixes:
- Conveyors in Sunnydale Mines should function as intended.
---
Additions:
- Gangs given far more weaponry and utility in their tool.
---
Changes:
- Motorcycle no longer tosses you off.
- Ghouls now drop caps.

Fixes & Additions

---

code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/projectile/bullets/shotgun.dm

Ok, so, we're back to normal. Turns out they're not that great.

Back to Normalcy

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm
code/modules/jobs/job_types/ncr.dm

Radios once again not standard issue. Six for NCR/Legion.

Radio Antichrist

---

code/__DEFINES/mobs.dm

Respawn Timer

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/BoxStation/Dungeons.dmm
_maps/map_files/Pahrump/Dungeons.dmm

fixed the commie vault med room gravity by changing the area to everything else, also changes the hydroponics room to the other area too
bad
:cl:
fix: commie vault med room
/:cl:

commie vault medical fix

---

_maps/boxstation.json

What could go wrong?
(only changes the title, not the pathing)

Rename Box Station to Sunnydale

---

interactions/lewd/objects.dm

With water, sodium, and lime juice, you can now make your own 100% natural human semen!
Uh... Because funni????????
Yeah, local testing worked really well.
:cl:
add: Added a way to create coom.
/:cl:

Literally Makes Coom Chemable

---

code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/guns/ballistic/shotgun.dm

guh
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Fixed Loadouts

---

code/modules/reagents/chemistry/reagents/other_reagents.dm
code/modules/reagents/chemistry/recipes/others.dm
code/modules/reagents/reagent_containers/pill.dm

Adds water purification tablets and a method to synthesize them.
All recipes and reagents have been tested.
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Water Purification Tablets

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm

- - -
Bug fixes.
- Corrects a space 'area' within the BoS bunker on Sunnydale.
- - -
Map:
- Correctly adds the areas required to the BoS bunkers on both maps.
- Adjusts the exit tunnel for the BoS on Pahrump.
- Removes the ten thousand something casings in the new NCR base. Gang gang.
- - -

Miscellaneous Corrections

---

.gitignore
tools/discord/.gitignore

Corrects a serious mistake.

---

code/_onclick/hud/fullscreen.dm
code/datums/components/mood.dm

Film grain for low mood.
It was on the "To do" list.
Went on a local hosted server, edited my mood manually, and observed the effects.
add: Film grains.

Film Grain

---

code/_onclick/hud/hud.dm

- - -
Notes:
- Completely changes the hud buttons, utilizing pre-existing sprites and sprite sheets. Credits in the PR prior to this.

Hud Changes

---

_maps/map_files/BoxStation/BoxStation.dmm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm

- - -
Map:
- NCR Bunker on Sunnydale given proper lighting.
- - -
Bugfixes:
- Healing Powder now properly processes.

Corrections + Powder Hotfix

---

tools/discord/config.yml
tools/discord/example_config/config.yml

updated discord config

---

_maps/map_files/BoxStation/BoxStation.dmm

Adds bunker area to the bunker so it's actually powered
shutup
hasn't, ligma
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

Area updated

---

code/datums/emotes.dm
code/modules/mob/mob.dm

Runtime Hotfix

---

_maps/map_files/BoxStation/BoxStation.dmm

- - -
Map:
- NCR base on Sunnydale has been expanded southwards somewhat, and the Ranger base has been removed.
- - -

Sunnydale Touchup

---

code/game/objects/items/storage/firstaid.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/ncr.dm
code/modules/mining/machine_vending.dm

Changes a few roles and kits in order to fit the upcoming changes to factions.
- Legionaire given a choice between Prime and Recruit.
> Recruit Legionary, sporting the weakest armor of the faction and the weakest  faction melee weapon. But have a somewhat alright ranged weapon, still sub-par to what is normally found.
> Prime Legionairy sports better armor and a stronger melee-weapon alongside the dreaded bola. But has a shitty 9mm pistol. They're all about closing the distance!
- Veteran Legionary crates now fun:tm:
- NCR jobs provided a few things. Including a MASSIVE buff to a specialist crate.
- Corpsman job added.

Anti-Bloat stuff

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/Pahrump/Pahrump.dmm
code/__DEFINES/traits.dm
code/datums/traits/good.dm
code/game/objects/effects/landmarks.dm
code/game/objects/items/weaponry.dm
code/modules/projectiles/boxes_magazines/internal/shotgun.dm

- - -
Map:
- NCR and Legion base on both maps mildly adjusted to account for the new roles.
- - -
Corrections:
- Shotguns use improvised shot by default if no others are specified.
- Other things.

Various Balance Changes

---

_maps/map_files/BoxStation/BoxStation.dmm

you already know, CARL
makes map better
tested but you should test it yourself probably
changes: made sunnydale better :)

Sunnydale changes

---

_maps/map_files/BoxStation/BoxStation.dmm
_maps/map_files/BoxStation/Dungeons.dmm
_maps/map_files/Pahrump/Dungeons.dmm
_maps/map_files/Pahrump/Pahrump.dmm
code/game/objects/effects/spawners/new_spawners.dm

- - -
Simply places the new tiers into the maps.
- - -

Tiers re-placed.

---

code/modules/reagents/chemistry/holder.dm

Fixes. Accept PR. Guh.
